version: '3.9'

volumes:
  go_full_database-data:
    external: false

services:
  go_full_database:
    container_name: go_full_database
    image: postgres:16.1-alpine
    restart: always
    volumes:
      - go_full_database-data:/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
